baseURL = "https://freundinnen-der-raaber-baeche.github.io/"
languageCode = "de-at"
title = "FreundInnen der Raaber BÃ¤che"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
paginate = 5

[params]
    dateFormatToUse = "02. 01. 2006"
    facebook = "RaaberBach"
